// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using backend.Infrastructure.Persistence;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308185016_HardenDatabaseSchema")]
    partial class HardenDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Modules.Inventories.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Equipment"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Book"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.CustomField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("field_type");

                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("ShowInTable")
                        .HasColumnType("boolean")
                        .HasColumnName("show_in_table");

                    b.Property<int>("SlotNo")
                        .HasColumnType("integer")
                        .HasColumnName("slot_no");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId", "FieldType", "SlotNo")
                        .IsUnique();

                    b.ToTable("custom_fields", null, t =>
                        {
                            t.HasCheckConstraint("ck_custom_fields_field_type", "field_type in ('single_line','multi_line','number','link','bool')");

                            t.HasCheckConstraint("ck_custom_fields_slot_no", "slot_no between 1 and 3");
                        });
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.CustomIdSequenceState", b =>
                {
                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InventoryId");

                    b.ToTable("custom_id_sequence_state", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.CustomIdTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationRegex")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("validation_regex");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId")
                        .IsUnique();

                    b.ToTable("custom_id_templates", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.CustomIdTemplatePart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FixedText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fixed_text");

                    b.Property<string>("FormatPattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("format_pattern");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("part_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "SortOrder")
                        .IsUnique();

                    b.ToTable("custom_id_template_parts", null, t =>
                        {
                            t.HasCheckConstraint("ck_custom_id_template_parts_part_type", "part_type in ('fixed_text','random_20_bit','random_32_bit','random_6_digit','random_9_digit','guid','datetime','sequence')");
                        });
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.DiscussionPost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_user_id");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("content_markdown");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("InventoryId", "Id");

                    b.ToTable("discussion_posts", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.Inventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<string>("DescriptionMarkdown")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description_markdown");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<NpgsqlTsVector>("search_vector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description_markdown, ''))", true);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("CreatorId");

                    b.HasIndex("search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("search_vector"), "GIN");

                    b.ToTable("inventories", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventories_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.InventoryAccess", b =>
                {
                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GrantedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("granted_by_user_id");

                    b.HasKey("InventoryId", "UserId");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("inventory_access", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.InventoryNumericFieldStatistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AvgValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("avg_value");

                    b.Property<long>("CustomFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("custom_field_id");

                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldId");

                    b.HasIndex("InventoryId", "CustomFieldId")
                        .IsUnique();

                    b.ToTable("inventory_numeric_field_statistics", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.InventoryStatistics", b =>
                {
                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<int>("ItemsCount")
                        .HasColumnType("integer")
                        .HasColumnName("items_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InventoryId");

                    b.HasIndex("ItemsCount")
                        .IsDescending();

                    b.ToTable("inventory_statistics", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.InventoryStringFieldStatistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("custom_field_id");

                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<int>("MostFrequentCount")
                        .HasColumnType("integer")
                        .HasColumnName("most_frequent_count");

                    b.Property<string>("MostFrequentValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("most_frequent_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldId");

                    b.HasIndex("InventoryId", "CustomFieldId")
                        .IsUnique();

                    b.ToTable("inventory_string_field_statistics", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.InventoryTag", b =>
                {
                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("InventoryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("inventory_tags", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.Property<NpgsqlTsVector>("search_vector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(name, ''))", true);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("search_vector"), "GIN");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Items.Domain.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("custom_id");

                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("InventoryId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("InventoryId", "CustomId")
                        .IsUnique();

                    b.ToTable("items", null, t =>
                        {
                            t.HasCheckConstraint("ck_items_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("backend.Modules.Items.Domain.ItemCustomFieldValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean")
                        .HasColumnName("bool_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("custom_field_id");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<string>("LinkValue")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("link_value");

                    b.Property<decimal?>("NumberValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("number_value");

                    b.Property<string>("StringValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("string_value");

                    b.Property<string>("TextValue")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("text_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<NpgsqlTsVector>("search_vector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(string_value, '') || ' ' || coalesce(text_value, '') || ' ' || coalesce(link_value, ''))", true);

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldId");

                    b.HasIndex("search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("search_vector"), "GIN");

                    b.HasIndex("ItemId", "CustomFieldId")
                        .IsUnique();

                    b.ToTable("item_custom_field_values", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_custom_field_values_single_value", "(case when string_value is not null then 1 else 0 end + case when text_value is not null then 1 else 0 end + case when number_value is not null then 1 else 0 end + case when link_value is not null then 1 else 0 end + case when bool_value is not null then 1 else 0 end) <= 1");
                        });
                });

            modelBuilder.Entity("backend.Modules.Items.Domain.ItemLike", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("item_likes", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Users.Domain.ExternalAuthAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_user_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("external_auth_accounts", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Users.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "user"
                        },
                        new
                        {
                            Id = 2,
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("backend.Modules.Users.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("PreferredTheme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_theme");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Users.Domain.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.CustomField", b =>
                {
                    b.HasOne("backend.Modules.Inventories.Domain.Inventory", "Inventory")
                        .WithMany("CustomFields")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.CustomIdSequenceState", b =>
                {
                    b.HasOne("backend.Modules.Inventories.Domain.Inventory", "Inventory")
                        .WithOne("CustomIdSequenceState")
                        .HasForeignKey("backend.Modules.Inventories.Domain.CustomIdSequenceState", "InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.CustomIdTemplate", b =>
                {
                    b.HasOne("backend.Modules.Inventories.Domain.Inventory", "Inventory")
                        .WithOne("CustomIdTemplate")
                        .HasForeignKey("backend.Modules.Inventories.Domain.CustomIdTemplate", "InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.CustomIdTemplatePart", b =>
                {
                    b.HasOne("backend.Modules.Inventories.Domain.CustomIdTemplate", "Template")
                        .WithMany("Parts")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.DiscussionPost", b =>
                {
                    b.HasOne("backend.Modules.Users.Domain.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Inventories.Domain.Inventory", "Inventory")
                        .WithMany("DiscussionPosts")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.Inventory", b =>
                {
                    b.HasOne("backend.Modules.Inventories.Domain.Category", "Category")
                        .WithMany("Inventories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Modules.Users.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.InventoryAccess", b =>
                {
                    b.HasOne("backend.Modules.Users.Domain.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Inventories.Domain.Inventory", "Inventory")
                        .WithMany("AccessList")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrantedByUser");

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.InventoryNumericFieldStatistic", b =>
                {
                    b.HasOne("backend.Modules.Inventories.Domain.CustomField", "CustomField")
                        .WithMany("NumericStatistics")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Inventories.Domain.Inventory", "Inventory")
                        .WithMany("NumericFieldStatistics")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomField");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.InventoryStatistics", b =>
                {
                    b.HasOne("backend.Modules.Inventories.Domain.Inventory", "Inventory")
                        .WithOne("Statistics")
                        .HasForeignKey("backend.Modules.Inventories.Domain.InventoryStatistics", "InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.InventoryStringFieldStatistic", b =>
                {
                    b.HasOne("backend.Modules.Inventories.Domain.CustomField", "CustomField")
                        .WithMany("StringStatistics")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Inventories.Domain.Inventory", "Inventory")
                        .WithMany("StringFieldStatistics")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomField");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.InventoryTag", b =>
                {
                    b.HasOne("backend.Modules.Inventories.Domain.Inventory", "Inventory")
                        .WithMany("InventoryTags")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Inventories.Domain.Tag", "Tag")
                        .WithMany("InventoryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("backend.Modules.Items.Domain.Item", b =>
                {
                    b.HasOne("backend.Modules.Users.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Modules.Inventories.Domain.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Users.Domain.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Inventory");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Modules.Items.Domain.ItemCustomFieldValue", b =>
                {
                    b.HasOne("backend.Modules.Inventories.Domain.CustomField", "CustomField")
                        .WithMany("Values")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Items.Domain.Item", "Item")
                        .WithMany("CustomFieldValues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomField");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("backend.Modules.Items.Domain.ItemLike", b =>
                {
                    b.HasOne("backend.Modules.Items.Domain.Item", "Item")
                        .WithMany("Likes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Modules.Users.Domain.ExternalAuthAccount", b =>
                {
                    b.HasOne("backend.Modules.Users.Domain.User", "User")
                        .WithMany("ExternalAuthAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Modules.Users.Domain.UserRole", b =>
                {
                    b.HasOne("backend.Modules.Users.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Users.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.Category", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.CustomField", b =>
                {
                    b.Navigation("NumericStatistics");

                    b.Navigation("StringStatistics");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.CustomIdTemplate", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.Inventory", b =>
                {
                    b.Navigation("AccessList");

                    b.Navigation("CustomFields");

                    b.Navigation("CustomIdSequenceState");

                    b.Navigation("CustomIdTemplate");

                    b.Navigation("DiscussionPosts");

                    b.Navigation("InventoryTags");

                    b.Navigation("Items");

                    b.Navigation("NumericFieldStatistics");

                    b.Navigation("Statistics");

                    b.Navigation("StringFieldStatistics");
                });

            modelBuilder.Entity("backend.Modules.Inventories.Domain.Tag", b =>
                {
                    b.Navigation("InventoryTags");
                });

            modelBuilder.Entity("backend.Modules.Items.Domain.Item", b =>
                {
                    b.Navigation("CustomFieldValues");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("backend.Modules.Users.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("backend.Modules.Users.Domain.User", b =>
                {
                    b.Navigation("ExternalAuthAccounts");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
